apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "asr-pro.fullname" . }}-backend
  labels:
    app: {{ include "asr-pro.fullname" . }}
    tier: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "asr-pro.fullname" . }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ include "asr-pro.fullname" . }}
        tier: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "asr-pro.fullname" . }}-secret
                  key: databaseUrl
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "asr-pro.fullname" . }}-secret
                  key: jwtSecret
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
