apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asr-pro.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "asr-pro.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  jwt-secret: {{ required "secrets.jwtKey is required" .Values.secrets.jwtKey | quote }}
  admin-password: {{ required "secrets.adminPassword is required" .Values.secrets.adminPassword | quote }}
